version: '3.7'

services:
  database:
    image: postgres:15-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-app}
    volumes:
      - "./tmp/postgres:/var/lib/postgresql/data:rw"
